services:
  - type: web
    name: indie-diva-hub
    env: docker
    plan: free
    repo: https://github.com/romanuspopulsque/IndieDivaHub
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: tvoj-host
      - key: DB_NAME
        value: indie_diva_hub
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: password
